title: "IF"
description: "Personal blog and project showcase"
author: "Igor"
url: "https://example.com"
social:
  GitHub: "https://github.com/IgorFroehner"
  X: "https://x.com/idk_the_if"
postsPerPage: 10
